// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: protoregistry/v1/registry.proto

package registrypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RegistryService_Publish_FullMethodName            = "/protoregistry.v1.RegistryService/Publish"
	RegistryService_Promote_FullMethodName            = "/protoregistry.v1.RegistryService/Promote"
	RegistryService_DiscardStaging_FullMethodName     = "/protoregistry.v1.RegistryService/DiscardStaging"
	RegistryService_Rollback_FullMethodName           = "/protoregistry.v1.RegistryService/Rollback"
	RegistryService_GetSchema_FullMethodName          = "/protoregistry.v1.RegistryService/GetSchema"
	RegistryService_ListSchemas_FullMethodName        = "/protoregistry.v1.RegistryService/ListSchemas"
	RegistryService_GetDescriptor_FullMethodName      = "/protoregistry.v1.RegistryService/GetDescriptor"
	RegistryService_GetSource_FullMethodName          = "/protoregistry.v1.RegistryService/GetSource"
	RegistryService_ListNamespaces_FullMethodName     = "/protoregistry.v1.RegistryService/ListNamespaces"
	RegistryService_CreateNamespace_FullMethodName    = "/protoregistry.v1.RegistryService/CreateNamespace"
	RegistryService_SetNamespaceParent_FullMethodName = "/protoregistry.v1.RegistryService/SetNamespaceParent"
	RegistryService_GetRebaseStatus_FullMethodName    = "/protoregistry.v1.RegistryService/GetRebaseStatus"
	RegistryService_Rebase_FullMethodName             = "/protoregistry.v1.RegistryService/Rebase"
	RegistryService_GetNamespaceChain_FullMethodName  = "/protoregistry.v1.RegistryService/GetNamespaceChain"
)

// RegistryServiceClient is the client API for RegistryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RegistryService provides a gRPC API for the proto schema registry.
type RegistryServiceClient interface {
	// Publish compiles and stages a new schema version within a namespace.
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
	// Promote atomically moves all staged versions to current in a namespace.
	Promote(ctx context.Context, in *PromoteRequest, opts ...grpc.CallOption) (*PromoteResponse, error)
	// DiscardStaging clears all staged versions in a namespace.
	DiscardStaging(ctx context.Context, in *DiscardStagingRequest, opts ...grpc.CallOption) (*DiscardStagingResponse, error)
	// Rollback stages a previous version for promotion.
	Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error)
	// GetSchema returns metadata for a schema.
	GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error)
	// ListSchemas lists all schemas in a namespace.
	ListSchemas(ctx context.Context, in *ListSchemasRequest, opts ...grpc.CallOption) (*ListSchemasResponse, error)
	// GetDescriptor returns the compiled FileDescriptorSet for a schema version.
	GetDescriptor(ctx context.Context, in *GetDescriptorRequest, opts ...grpc.CallOption) (*GetDescriptorResponse, error)
	// GetSource returns the original source files for a schema version.
	GetSource(ctx context.Context, in *GetSourceRequest, opts ...grpc.CallOption) (*GetSourceResponse, error)
	// ListNamespaces lists all namespaces.
	ListNamespaces(ctx context.Context, in *ListNamespacesRequest, opts ...grpc.CallOption) (*ListNamespacesResponse, error)
	// CreateNamespace creates a new namespace.
	CreateNamespace(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*CreateNamespaceResponse, error)
	// SetNamespaceParent re-parents an existing namespace in the resolution
	// chain. Recorded in an append-only audit log (see decision D9). Gated
	// by the deployment's Authorizer.
	SetNamespaceParent(ctx context.Context, in *SetNamespaceParentRequest, opts ...grpc.CallOption) (*SetNamespaceParentResponse, error)
	// GetRebaseStatus reports, for a child schema's current version, which
	// pinned cross-namespace dependencies are behind the parent's current
	// state. Idempotent and read-only.
	GetRebaseStatus(ctx context.Context, in *GetRebaseStatusRequest, opts ...grpc.CallOption) (*GetRebaseStatusResponse, error)
	// Rebase re-resolves a child schema's parent chain against the parent's
	// current state and publishes a new version. Sources are unchanged; the
	// per-import pins (see decision D3) are refreshed. Gated by the
	// deployment's Authorizer.
	Rebase(ctx context.Context, in *RebaseRequest, opts ...grpc.CallOption) (*RebaseResponse, error)
	// GetNamespaceChain returns the resolution chain for a namespace as
	// an ordered slice of namespace IDs (child-first). Used by clients
	// that want to mirror the server's authoritative hierarchy view —
	// e.g., the SDK's WithServerChain option that auto-configures
	// ancestor resolvers as parents. Read-only.
	GetNamespaceChain(ctx context.Context, in *GetNamespaceChainRequest, opts ...grpc.CallOption) (*GetNamespaceChainResponse, error)
}

type registryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistryServiceClient(cc grpc.ClientConnInterface) RegistryServiceClient {
	return &registryServiceClient{cc}
}

func (c *registryServiceClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, RegistryService_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) Promote(ctx context.Context, in *PromoteRequest, opts ...grpc.CallOption) (*PromoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromoteResponse)
	err := c.cc.Invoke(ctx, RegistryService_Promote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) DiscardStaging(ctx context.Context, in *DiscardStagingRequest, opts ...grpc.CallOption) (*DiscardStagingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscardStagingResponse)
	err := c.cc.Invoke(ctx, RegistryService_DiscardStaging_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackResponse)
	err := c.cc.Invoke(ctx, RegistryService_Rollback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSchemaResponse)
	err := c.cc.Invoke(ctx, RegistryService_GetSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) ListSchemas(ctx context.Context, in *ListSchemasRequest, opts ...grpc.CallOption) (*ListSchemasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSchemasResponse)
	err := c.cc.Invoke(ctx, RegistryService_ListSchemas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) GetDescriptor(ctx context.Context, in *GetDescriptorRequest, opts ...grpc.CallOption) (*GetDescriptorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDescriptorResponse)
	err := c.cc.Invoke(ctx, RegistryService_GetDescriptor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) GetSource(ctx context.Context, in *GetSourceRequest, opts ...grpc.CallOption) (*GetSourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSourceResponse)
	err := c.cc.Invoke(ctx, RegistryService_GetSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) ListNamespaces(ctx context.Context, in *ListNamespacesRequest, opts ...grpc.CallOption) (*ListNamespacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNamespacesResponse)
	err := c.cc.Invoke(ctx, RegistryService_ListNamespaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) CreateNamespace(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*CreateNamespaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNamespaceResponse)
	err := c.cc.Invoke(ctx, RegistryService_CreateNamespace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) SetNamespaceParent(ctx context.Context, in *SetNamespaceParentRequest, opts ...grpc.CallOption) (*SetNamespaceParentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetNamespaceParentResponse)
	err := c.cc.Invoke(ctx, RegistryService_SetNamespaceParent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) GetRebaseStatus(ctx context.Context, in *GetRebaseStatusRequest, opts ...grpc.CallOption) (*GetRebaseStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRebaseStatusResponse)
	err := c.cc.Invoke(ctx, RegistryService_GetRebaseStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) Rebase(ctx context.Context, in *RebaseRequest, opts ...grpc.CallOption) (*RebaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RebaseResponse)
	err := c.cc.Invoke(ctx, RegistryService_Rebase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) GetNamespaceChain(ctx context.Context, in *GetNamespaceChainRequest, opts ...grpc.CallOption) (*GetNamespaceChainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNamespaceChainResponse)
	err := c.cc.Invoke(ctx, RegistryService_GetNamespaceChain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryServiceServer is the server API for RegistryService service.
// All implementations must embed UnimplementedRegistryServiceServer
// for forward compatibility.
//
// RegistryService provides a gRPC API for the proto schema registry.
type RegistryServiceServer interface {
	// Publish compiles and stages a new schema version within a namespace.
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
	// Promote atomically moves all staged versions to current in a namespace.
	Promote(context.Context, *PromoteRequest) (*PromoteResponse, error)
	// DiscardStaging clears all staged versions in a namespace.
	DiscardStaging(context.Context, *DiscardStagingRequest) (*DiscardStagingResponse, error)
	// Rollback stages a previous version for promotion.
	Rollback(context.Context, *RollbackRequest) (*RollbackResponse, error)
	// GetSchema returns metadata for a schema.
	GetSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error)
	// ListSchemas lists all schemas in a namespace.
	ListSchemas(context.Context, *ListSchemasRequest) (*ListSchemasResponse, error)
	// GetDescriptor returns the compiled FileDescriptorSet for a schema version.
	GetDescriptor(context.Context, *GetDescriptorRequest) (*GetDescriptorResponse, error)
	// GetSource returns the original source files for a schema version.
	GetSource(context.Context, *GetSourceRequest) (*GetSourceResponse, error)
	// ListNamespaces lists all namespaces.
	ListNamespaces(context.Context, *ListNamespacesRequest) (*ListNamespacesResponse, error)
	// CreateNamespace creates a new namespace.
	CreateNamespace(context.Context, *CreateNamespaceRequest) (*CreateNamespaceResponse, error)
	// SetNamespaceParent re-parents an existing namespace in the resolution
	// chain. Recorded in an append-only audit log (see decision D9). Gated
	// by the deployment's Authorizer.
	SetNamespaceParent(context.Context, *SetNamespaceParentRequest) (*SetNamespaceParentResponse, error)
	// GetRebaseStatus reports, for a child schema's current version, which
	// pinned cross-namespace dependencies are behind the parent's current
	// state. Idempotent and read-only.
	GetRebaseStatus(context.Context, *GetRebaseStatusRequest) (*GetRebaseStatusResponse, error)
	// Rebase re-resolves a child schema's parent chain against the parent's
	// current state and publishes a new version. Sources are unchanged; the
	// per-import pins (see decision D3) are refreshed. Gated by the
	// deployment's Authorizer.
	Rebase(context.Context, *RebaseRequest) (*RebaseResponse, error)
	// GetNamespaceChain returns the resolution chain for a namespace as
	// an ordered slice of namespace IDs (child-first). Used by clients
	// that want to mirror the server's authoritative hierarchy view —
	// e.g., the SDK's WithServerChain option that auto-configures
	// ancestor resolvers as parents. Read-only.
	GetNamespaceChain(context.Context, *GetNamespaceChainRequest) (*GetNamespaceChainResponse, error)
	mustEmbedUnimplementedRegistryServiceServer()
}

// UnimplementedRegistryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegistryServiceServer struct{}

func (UnimplementedRegistryServiceServer) Publish(context.Context, *PublishRequest) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedRegistryServiceServer) Promote(context.Context, *PromoteRequest) (*PromoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Promote not implemented")
}
func (UnimplementedRegistryServiceServer) DiscardStaging(context.Context, *DiscardStagingRequest) (*DiscardStagingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiscardStaging not implemented")
}
func (UnimplementedRegistryServiceServer) Rollback(context.Context, *RollbackRequest) (*RollbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rollback not implemented")
}
func (UnimplementedRegistryServiceServer) GetSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSchema not implemented")
}
func (UnimplementedRegistryServiceServer) ListSchemas(context.Context, *ListSchemasRequest) (*ListSchemasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSchemas not implemented")
}
func (UnimplementedRegistryServiceServer) GetDescriptor(context.Context, *GetDescriptorRequest) (*GetDescriptorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDescriptor not implemented")
}
func (UnimplementedRegistryServiceServer) GetSource(context.Context, *GetSourceRequest) (*GetSourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSource not implemented")
}
func (UnimplementedRegistryServiceServer) ListNamespaces(context.Context, *ListNamespacesRequest) (*ListNamespacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNamespaces not implemented")
}
func (UnimplementedRegistryServiceServer) CreateNamespace(context.Context, *CreateNamespaceRequest) (*CreateNamespaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNamespace not implemented")
}
func (UnimplementedRegistryServiceServer) SetNamespaceParent(context.Context, *SetNamespaceParentRequest) (*SetNamespaceParentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetNamespaceParent not implemented")
}
func (UnimplementedRegistryServiceServer) GetRebaseStatus(context.Context, *GetRebaseStatusRequest) (*GetRebaseStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRebaseStatus not implemented")
}
func (UnimplementedRegistryServiceServer) Rebase(context.Context, *RebaseRequest) (*RebaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rebase not implemented")
}
func (UnimplementedRegistryServiceServer) GetNamespaceChain(context.Context, *GetNamespaceChainRequest) (*GetNamespaceChainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNamespaceChain not implemented")
}
func (UnimplementedRegistryServiceServer) mustEmbedUnimplementedRegistryServiceServer() {}
func (UnimplementedRegistryServiceServer) testEmbeddedByValue()                         {}

// UnsafeRegistryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistryServiceServer will
// result in compilation errors.
type UnsafeRegistryServiceServer interface {
	mustEmbedUnimplementedRegistryServiceServer()
}

func RegisterRegistryServiceServer(s grpc.ServiceRegistrar, srv RegistryServiceServer) {
	// If the following call panics, it indicates UnimplementedRegistryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RegistryService_ServiceDesc, srv)
}

func _RegistryService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_Promote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).Promote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_Promote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).Promote(ctx, req.(*PromoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_DiscardStaging_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscardStagingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).DiscardStaging(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_DiscardStaging_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).DiscardStaging(ctx, req.(*DiscardStagingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_Rollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).Rollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_Rollback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).Rollback(ctx, req.(*RollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_GetSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).GetSchema(ctx, req.(*GetSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_ListSchemas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSchemasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).ListSchemas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_ListSchemas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).ListSchemas(ctx, req.(*ListSchemasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_GetDescriptor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDescriptorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).GetDescriptor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_GetDescriptor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).GetDescriptor(ctx, req.(*GetDescriptorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_GetSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).GetSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_GetSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).GetSource(ctx, req.(*GetSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_ListNamespaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNamespacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).ListNamespaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_ListNamespaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).ListNamespaces(ctx, req.(*ListNamespacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_CreateNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).CreateNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_CreateNamespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).CreateNamespace(ctx, req.(*CreateNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_SetNamespaceParent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNamespaceParentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).SetNamespaceParent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_SetNamespaceParent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).SetNamespaceParent(ctx, req.(*SetNamespaceParentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_GetRebaseStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRebaseStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).GetRebaseStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_GetRebaseStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).GetRebaseStatus(ctx, req.(*GetRebaseStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_Rebase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).Rebase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_Rebase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).Rebase(ctx, req.(*RebaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_GetNamespaceChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNamespaceChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).GetNamespaceChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_GetNamespaceChain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).GetNamespaceChain(ctx, req.(*GetNamespaceChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegistryService_ServiceDesc is the grpc.ServiceDesc for RegistryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegistryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protoregistry.v1.RegistryService",
	HandlerType: (*RegistryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _RegistryService_Publish_Handler,
		},
		{
			MethodName: "Promote",
			Handler:    _RegistryService_Promote_Handler,
		},
		{
			MethodName: "DiscardStaging",
			Handler:    _RegistryService_DiscardStaging_Handler,
		},
		{
			MethodName: "Rollback",
			Handler:    _RegistryService_Rollback_Handler,
		},
		{
			MethodName: "GetSchema",
			Handler:    _RegistryService_GetSchema_Handler,
		},
		{
			MethodName: "ListSchemas",
			Handler:    _RegistryService_ListSchemas_Handler,
		},
		{
			MethodName: "GetDescriptor",
			Handler:    _RegistryService_GetDescriptor_Handler,
		},
		{
			MethodName: "GetSource",
			Handler:    _RegistryService_GetSource_Handler,
		},
		{
			MethodName: "ListNamespaces",
			Handler:    _RegistryService_ListNamespaces_Handler,
		},
		{
			MethodName: "CreateNamespace",
			Handler:    _RegistryService_CreateNamespace_Handler,
		},
		{
			MethodName: "SetNamespaceParent",
			Handler:    _RegistryService_SetNamespaceParent_Handler,
		},
		{
			MethodName: "GetRebaseStatus",
			Handler:    _RegistryService_GetRebaseStatus_Handler,
		},
		{
			MethodName: "Rebase",
			Handler:    _RegistryService_Rebase_Handler,
		},
		{
			MethodName: "GetNamespaceChain",
			Handler:    _RegistryService_GetNamespaceChain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protoregistry/v1/registry.proto",
}
