// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: protoregistry/v1/registry.proto

package registrypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	SchemaId    string                 `protobuf:"bytes,2,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	// Source proto files: filename → content.
	Sources   map[string][]byte `protobuf:"bytes,3,rep,name=sources,proto3" json:"sources,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedBy string            `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Metadata  map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// When true, allows publishing files that shadow well-known types
	// (e.g., google/protobuf/timestamp.proto). Defaults to false.
	//
	// The server requires the caller to have admin privileges to set this
	// flag; non-admin callers will receive PERMISSION_DENIED.
	Force         bool `protobuf:"varint,6,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_protoregistry_v1_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoregistry_v1_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_protoregistry_v1_registry_proto_rawDescGZIP(), []int{0}
}

func (x *PublishRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *PublishRequest) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *PublishRequest) GetSources() map[string][]byte {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *PublishRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *PublishRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PublishRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Fingerprint   string                 `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	NoChange      bool                   `protobuf:"varint,3,opt,name=no_change,json=noChange,proto3" json:"no_change,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_protoregistry_v1_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoregistry_v1_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_protoregistry_v1_registry_proto_rawDescGZIP(), []int{1}
}

func (x *PublishResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PublishResponse) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *PublishResponse) GetNoChange() bool {
	if x != nil {
		return x.NoChange
	}
	return false
}

type PromoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoteRequest) Reset() {
	*x = PromoteRequest{}
	mi := &file_protoregistry_v1_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteRequest) ProtoMessage() {}

func (x *PromoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoregistry_v1_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteRequest.ProtoReflect.Descriptor instead.
func (*PromoteRequest) Descriptor() ([]byte, []int) {
	return file_protoregistry_v1_registry_proto_rawDescGZIP(), []int{2}
}

func (x *PromoteRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

type PromoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Promoted      []*PromotedSchema      `protobuf:"bytes,1,rep,name=promoted,proto3" json:"promoted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoteResponse) Reset() {
	*x = PromoteResponse{}
	mi := &file_protoregistry_v1_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteResponse) ProtoMessage() {}

func (x *PromoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoregistry_v1_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteResponse.ProtoReflect.Descriptor instead.
func (*PromoteResponse) Descriptor() ([]byte, []int) {
	return file_protoregistry_v1_registry_proto_rawDescGZIP(), []int{3}
}

func (x *PromoteResponse) GetPromoted() []*PromotedSchema {
	if x != nil {
		return x.Promoted
	}
	return nil
}

type PromotedSchema struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SchemaId       string                 `protobuf:"bytes,1,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	CurrentVersion uint64                 `protobuf:"varint,2,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PromotedSchema) Reset() {
	*x = PromotedSchema{}
	mi := &file_protoregistry_v1_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromotedSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromotedSchema) ProtoMessage() {}

func (x *PromotedSchema) ProtoReflect() protoreflect.Message {
	mi := &file_protoregistry_v1_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromotedSchema.ProtoReflect.Descriptor instead.
func (*PromotedSchema) Descriptor() ([]byte, []int) {
	return file_protoregistry_v1_registry_proto_rawDescGZIP(), []int{4}
}

func (x *PromotedSchema) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *PromotedSchema) GetCurrentVersion() uint64 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

type DiscardStagingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscardStagingRequest) Reset() {
	*x = DiscardStagingRequest{}
	mi := &file_protoregistry_v1_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscardStagingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscardStagingRequest) ProtoMessage() {}

func (x *DiscardStagingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoregistry_v1_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscardStagingRequest.ProtoReflect.Descriptor instead.
func (*DiscardStagingRequest) Descriptor() ([]byte, []int) {
	return file_protoregistry_v1_registry_proto_rawDescGZIP(), []int{5}
}

func (x *DiscardStagingRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

type DiscardStagingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscardStagingResponse) Reset() {
	*x = DiscardStagingResponse{}
	mi := &file_protoregistry_v1_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscardStagingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscardStagingResponse) ProtoMessage() {}

func (x *DiscardStagingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoregistry_v1_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscardStagingResponse.ProtoReflect.Descriptor instead.
func (*DiscardStagingResponse) Descriptor() ([]byte, []int) {
	return file_protoregistry_v1_registry_proto_rawDescGZIP(), []int{6}
}

type RollbackRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	SchemaId    string                 `protobuf:"bytes,2,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	Version     uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	// When true, the server bypasses the compat check that would otherwise
	// reject a rollback whose target version is not API-backward-compatible
	// with the current version. Intended for incident response.
	//
	// The server requires the caller to have admin privileges to set this
	// flag; non-admin callers will receive PERMISSION_DENIED.
	Force         bool `protobuf:"varint,4,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackRequest) Reset() {
	*x = RollbackRequest{}
	mi := &file_protoregistry_v1_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackRequest) ProtoMessage() {}

func (x *RollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoregistry_v1_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackRequest.ProtoReflect.Descriptor instead.
func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return file_protoregistry_v1_registry_proto_rawDescGZIP(), []int{7}
}

func (x *RollbackRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *RollbackRequest) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *RollbackRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RollbackRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type RollbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackResponse) Reset() {
	*x = RollbackResponse{}
	mi := &file_protoregistry_v1_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackResponse) ProtoMessage() {}

func (x *RollbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoregistry_v1_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackResponse.ProtoReflect.Descriptor instead.
func (*RollbackResponse) Descriptor() ([]byte, []int) {
	return file_protoregistry_v1_registry_proto_rawDescGZIP(), []int{8}
}

type GetSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	SchemaId      string                 `protobuf:"bytes,2,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaRequest) Reset() {
	*x = GetSchemaRequest{}
	mi := &file_protoregistry_v1_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaRequest) ProtoMessage() {}

func (x *GetSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoregistry_v1_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetSchemaRequest) Descriptor() ([]byte, []int) {
	return file_protoregistry_v1_registry_proto_rawDescGZIP(), []int{9}
}

func (x *GetSchemaRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *GetSchemaRequest) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

type GetSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        *SchemaInfo            `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaResponse) Reset() {
	*x = GetSchemaResponse{}
	mi := &file_protoregistry_v1_registry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaResponse) ProtoMessage() {}

func (x *GetSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoregistry_v1_registry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetSchemaResponse) Descriptor() ([]byte, []int) {
	return file_protoregistry_v1_registry_proto_rawDescGZIP(), []int{10}
}

func (x *GetSchemaResponse) GetSchema() *SchemaInfo {
	if x != nil {
		return x.Schema
	}
	return nil
}

type SchemaInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId    string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	SchemaId       string                 `protobuf:"bytes,2,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	CurrentVersion *uint64                `protobuf:"varint,3,opt,name=current_version,json=currentVersion,proto3,oneof" json:"current_version,omitempty"`
	StagedVersion  *uint64                `protobuf:"varint,4,opt,name=staged_version,json=stagedVersion,proto3,oneof" json:"staged_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Versions       []uint64               `protobuf:"varint,7,rep,packed,name=versions,proto3" json:"versions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SchemaInfo) Reset() {
	*x = SchemaInfo{}
	mi := &file_protoregistry_v1_registry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaInfo) ProtoMessage() {}

func (x *SchemaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protoregistry_v1_registry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaInfo.ProtoReflect.Descriptor instead.
func (*SchemaInfo) Descriptor() ([]byte, []int) {
	return file_protoregistry_v1_registry_proto_rawDescGZIP(), []int{11}
}

func (x *SchemaInfo) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *SchemaInfo) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *SchemaInfo) GetCurrentVersion() uint64 {
	if x != nil && x.CurrentVersion != nil {
		return *x.CurrentVersion
	}
	return 0
}

func (x *SchemaInfo) GetStagedVersion() uint64 {
	if x != nil && x.StagedVersion != nil {
		return *x.StagedVersion
	}
	return 0
}

func (x *SchemaInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SchemaInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SchemaInfo) GetVersions() []uint64 {
	if x != nil {
		return x.Versions
	}
	return nil
}

type ListSchemasRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	// Maximum number of schemas to return. 0 means use the server default.
	// The server may cap this; the cap is reflected in the next_page_token.
	PageSize uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Opaque token returned by a prior call's next_page_token. Empty for the
	// first page. Tokens are valid only against the same namespace.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchemasRequest) Reset() {
	*x = ListSchemasRequest{}
	mi := &file_protoregistry_v1_registry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchemasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchemasRequest) ProtoMessage() {}

func (x *ListSchemasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoregistry_v1_registry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchemasRequest.ProtoReflect.Descriptor instead.
func (*ListSchemasRequest) Descriptor() ([]byte, []int) {
	return file_protoregistry_v1_registry_proto_rawDescGZIP(), []int{12}
}

func (x *ListSchemasRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *ListSchemasRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSchemasRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListSchemasResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Schemas []*SchemaInfo          `protobuf:"bytes,1,rep,name=schemas,proto3" json:"schemas,omitempty"`
	// Token to pass as page_token in the next call to fetch more results.
	// Empty when there are no more pages.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchemasResponse) Reset() {
	*x = ListSchemasResponse{}
	mi := &file_protoregistry_v1_registry_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchemasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchemasResponse) ProtoMessage() {}

func (x *ListSchemasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoregistry_v1_registry_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchemasResponse.ProtoReflect.Descriptor instead.
func (*ListSchemasResponse) Descriptor() ([]byte, []int) {
	return file_protoregistry_v1_registry_proto_rawDescGZIP(), []int{13}
}

func (x *ListSchemasResponse) GetSchemas() []*SchemaInfo {
	if x != nil {
		return x.Schemas
	}
	return nil
}

func (x *ListSchemasResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetDescriptorRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	SchemaId    string                 `protobuf:"bytes,2,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	// If 0, returns the current version.
	Version       uint64 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDescriptorRequest) Reset() {
	*x = GetDescriptorRequest{}
	mi := &file_protoregistry_v1_registry_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDescriptorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDescriptorRequest) ProtoMessage() {}

func (x *GetDescriptorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoregistry_v1_registry_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDescriptorRequest.ProtoReflect.Descriptor instead.
func (*GetDescriptorRequest) Descriptor() ([]byte, []int) {
	return file_protoregistry_v1_registry_proto_rawDescGZIP(), []int{14}
}

func (x *GetDescriptorRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *GetDescriptorRequest) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *GetDescriptorRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetDescriptorResponse struct {
	state             protoimpl.MessageState          `protogen:"open.v1"`
	Version           uint64                          `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	FileDescriptorSet *descriptorpb.FileDescriptorSet `protobuf:"bytes,2,opt,name=file_descriptor_set,json=fileDescriptorSet,proto3" json:"file_descriptor_set,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetDescriptorResponse) Reset() {
	*x = GetDescriptorResponse{}
	mi := &file_protoregistry_v1_registry_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDescriptorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDescriptorResponse) ProtoMessage() {}

func (x *GetDescriptorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoregistry_v1_registry_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDescriptorResponse.ProtoReflect.Descriptor instead.
func (*GetDescriptorResponse) Descriptor() ([]byte, []int) {
	return file_protoregistry_v1_registry_proto_rawDescGZIP(), []int{15}
}

func (x *GetDescriptorResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetDescriptorResponse) GetFileDescriptorSet() *descriptorpb.FileDescriptorSet {
	if x != nil {
		return x.FileDescriptorSet
	}
	return nil
}

type GetSourceRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	SchemaId    string                 `protobuf:"bytes,2,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	// If 0, returns the current version.
	Version       uint64 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSourceRequest) Reset() {
	*x = GetSourceRequest{}
	mi := &file_protoregistry_v1_registry_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSourceRequest) ProtoMessage() {}

func (x *GetSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoregistry_v1_registry_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSourceRequest.ProtoReflect.Descriptor instead.
func (*GetSourceRequest) Descriptor() ([]byte, []int) {
	return file_protoregistry_v1_registry_proto_rawDescGZIP(), []int{16}
}

func (x *GetSourceRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *GetSourceRequest) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *GetSourceRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetSourceResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// filename → source content.
	Sources       map[string][]byte `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSourceResponse) Reset() {
	*x = GetSourceResponse{}
	mi := &file_protoregistry_v1_registry_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSourceResponse) ProtoMessage() {}

func (x *GetSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoregistry_v1_registry_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSourceResponse.ProtoReflect.Descriptor instead.
func (*GetSourceResponse) Descriptor() ([]byte, []int) {
	return file_protoregistry_v1_registry_proto_rawDescGZIP(), []int{17}
}

func (x *GetSourceResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetSourceResponse) GetSources() map[string][]byte {
	if x != nil {
		return x.Sources
	}
	return nil
}

type ListNamespacesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of namespaces to return. 0 means use the server default.
	PageSize uint32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Opaque token returned by a prior call's next_page_token. Empty for the
	// first page.
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNamespacesRequest) Reset() {
	*x = ListNamespacesRequest{}
	mi := &file_protoregistry_v1_registry_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNamespacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamespacesRequest) ProtoMessage() {}

func (x *ListNamespacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoregistry_v1_registry_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamespacesRequest.ProtoReflect.Descriptor instead.
func (*ListNamespacesRequest) Descriptor() ([]byte, []int) {
	return file_protoregistry_v1_registry_proto_rawDescGZIP(), []int{18}
}

func (x *ListNamespacesRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListNamespacesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListNamespacesResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Namespaces []*NamespaceInfo       `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	// Token to pass as page_token in the next call to fetch more results.
	// Empty when there are no more pages.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNamespacesResponse) Reset() {
	*x = ListNamespacesResponse{}
	mi := &file_protoregistry_v1_registry_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNamespacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamespacesResponse) ProtoMessage() {}

func (x *ListNamespacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoregistry_v1_registry_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamespacesResponse.ProtoReflect.Descriptor instead.
func (*ListNamespacesResponse) Descriptor() ([]byte, []int) {
	return file_protoregistry_v1_registry_proto_rawDescGZIP(), []int{19}
}

func (x *ListNamespacesResponse) GetNamespaces() []*NamespaceInfo {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *ListNamespacesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type NamespaceInfo struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Metadata  map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Parent namespace in the resolution chain. Unset means this namespace
	// is a root (resolution falls back to the implicit __builtins__ and
	// then to Google WKT). Wired into resolution by phase 2 of the
	// namespace-hierarchy work; see docs/design/namespace-hierarchy.md.
	ParentNamespaceId *string `protobuf:"bytes,4,opt,name=parent_namespace_id,json=parentNamespaceId,proto3,oneof" json:"parent_namespace_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NamespaceInfo) Reset() {
	*x = NamespaceInfo{}
	mi := &file_protoregistry_v1_registry_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceInfo) ProtoMessage() {}

func (x *NamespaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protoregistry_v1_registry_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceInfo.ProtoReflect.Descriptor instead.
func (*NamespaceInfo) Descriptor() ([]byte, []int) {
	return file_protoregistry_v1_registry_proto_rawDescGZIP(), []int{20}
}

func (x *NamespaceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NamespaceInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *NamespaceInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *NamespaceInfo) GetParentNamespaceId() string {
	if x != nil && x.ParentNamespaceId != nil {
		return *x.ParentNamespaceId
	}
	return ""
}

type CreateNamespaceRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Metadata map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional parent namespace for the resolution chain. The server
	// verifies the parent exists and that the caller is authorized to
	// create a namespace under it (see authz.CanCreateNamespace in
	// docs/design/namespace-hierarchy.md).
	ParentNamespaceId *string `protobuf:"bytes,3,opt,name=parent_namespace_id,json=parentNamespaceId,proto3,oneof" json:"parent_namespace_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateNamespaceRequest) Reset() {
	*x = CreateNamespaceRequest{}
	mi := &file_protoregistry_v1_registry_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNamespaceRequest) ProtoMessage() {}

func (x *CreateNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoregistry_v1_registry_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNamespaceRequest.ProtoReflect.Descriptor instead.
func (*CreateNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_protoregistry_v1_registry_proto_rawDescGZIP(), []int{21}
}

func (x *CreateNamespaceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateNamespaceRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateNamespaceRequest) GetParentNamespaceId() string {
	if x != nil && x.ParentNamespaceId != nil {
		return *x.ParentNamespaceId
	}
	return ""
}

type CreateNamespaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNamespaceResponse) Reset() {
	*x = CreateNamespaceResponse{}
	mi := &file_protoregistry_v1_registry_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNamespaceResponse) ProtoMessage() {}

func (x *CreateNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoregistry_v1_registry_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNamespaceResponse.ProtoReflect.Descriptor instead.
func (*CreateNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_protoregistry_v1_registry_proto_rawDescGZIP(), []int{22}
}

type SetNamespaceParentRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	// Unset clears the parent (resets the namespace to the implicit root,
	// which falls back to __builtins__ and then Google WKT).
	ParentNamespaceId *string `protobuf:"bytes,2,opt,name=parent_namespace_id,json=parentNamespaceId,proto3,oneof" json:"parent_namespace_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SetNamespaceParentRequest) Reset() {
	*x = SetNamespaceParentRequest{}
	mi := &file_protoregistry_v1_registry_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNamespaceParentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNamespaceParentRequest) ProtoMessage() {}

func (x *SetNamespaceParentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoregistry_v1_registry_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNamespaceParentRequest.ProtoReflect.Descriptor instead.
func (*SetNamespaceParentRequest) Descriptor() ([]byte, []int) {
	return file_protoregistry_v1_registry_proto_rawDescGZIP(), []int{23}
}

func (x *SetNamespaceParentRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *SetNamespaceParentRequest) GetParentNamespaceId() string {
	if x != nil && x.ParentNamespaceId != nil {
		return *x.ParentNamespaceId
	}
	return ""
}

type SetNamespaceParentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNamespaceParentResponse) Reset() {
	*x = SetNamespaceParentResponse{}
	mi := &file_protoregistry_v1_registry_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNamespaceParentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNamespaceParentResponse) ProtoMessage() {}

func (x *SetNamespaceParentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoregistry_v1_registry_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNamespaceParentResponse.ProtoReflect.Descriptor instead.
func (*SetNamespaceParentResponse) Descriptor() ([]byte, []int) {
	return file_protoregistry_v1_registry_proto_rawDescGZIP(), []int{24}
}

type GetRebaseStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	SchemaId      string                 `protobuf:"bytes,2,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRebaseStatusRequest) Reset() {
	*x = GetRebaseStatusRequest{}
	mi := &file_protoregistry_v1_registry_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRebaseStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRebaseStatusRequest) ProtoMessage() {}

func (x *GetRebaseStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoregistry_v1_registry_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRebaseStatusRequest.ProtoReflect.Descriptor instead.
func (*GetRebaseStatusRequest) Descriptor() ([]byte, []int) {
	return file_protoregistry_v1_registry_proto_rawDescGZIP(), []int{25}
}

func (x *GetRebaseStatusRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *GetRebaseStatusRequest) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

type GetRebaseStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One status per cross-namespace dependency. Same-namespace deps are
	// not included. Empty when this schema has no parent-chain pins.
	PinStatuses []*ParentPinStatus `protobuf:"bytes,1,rep,name=pin_statuses,json=pinStatuses,proto3" json:"pin_statuses,omitempty"`
	// True if any pin is behind the parent's current state.
	RebaseAvailable bool `protobuf:"varint,2,opt,name=rebase_available,json=rebaseAvailable,proto3" json:"rebase_available,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRebaseStatusResponse) Reset() {
	*x = GetRebaseStatusResponse{}
	mi := &file_protoregistry_v1_registry_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRebaseStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRebaseStatusResponse) ProtoMessage() {}

func (x *GetRebaseStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoregistry_v1_registry_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRebaseStatusResponse.ProtoReflect.Descriptor instead.
func (*GetRebaseStatusResponse) Descriptor() ([]byte, []int) {
	return file_protoregistry_v1_registry_proto_rawDescGZIP(), []int{26}
}

func (x *GetRebaseStatusResponse) GetPinStatuses() []*ParentPinStatus {
	if x != nil {
		return x.PinStatuses
	}
	return nil
}

func (x *GetRebaseStatusResponse) GetRebaseAvailable() bool {
	if x != nil {
		return x.RebaseAvailable
	}
	return false
}

type ParentPinStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ParentNamespaceId string                 `protobuf:"bytes,1,opt,name=parent_namespace_id,json=parentNamespaceId,proto3" json:"parent_namespace_id,omitempty"`
	DepSchemaId       string                 `protobuf:"bytes,2,opt,name=dep_schema_id,json=depSchemaId,proto3" json:"dep_schema_id,omitempty"`
	DepFilename       string                 `protobuf:"bytes,3,opt,name=dep_filename,json=depFilename,proto3" json:"dep_filename,omitempty"`
	PinnedVersion     uint64                 `protobuf:"varint,4,opt,name=pinned_version,json=pinnedVersion,proto3" json:"pinned_version,omitempty"`
	// Parent's current version of (dep_schema_id, dep_filename). Zero
	// when the schema or file no longer exists in the parent — in that
	// case a rebase would fail because the pinned file vanished.
	CurrentVersion uint64 `protobuf:"varint,5,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ParentPinStatus) Reset() {
	*x = ParentPinStatus{}
	mi := &file_protoregistry_v1_registry_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParentPinStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentPinStatus) ProtoMessage() {}

func (x *ParentPinStatus) ProtoReflect() protoreflect.Message {
	mi := &file_protoregistry_v1_registry_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentPinStatus.ProtoReflect.Descriptor instead.
func (*ParentPinStatus) Descriptor() ([]byte, []int) {
	return file_protoregistry_v1_registry_proto_rawDescGZIP(), []int{27}
}

func (x *ParentPinStatus) GetParentNamespaceId() string {
	if x != nil {
		return x.ParentNamespaceId
	}
	return ""
}

func (x *ParentPinStatus) GetDepSchemaId() string {
	if x != nil {
		return x.DepSchemaId
	}
	return ""
}

func (x *ParentPinStatus) GetDepFilename() string {
	if x != nil {
		return x.DepFilename
	}
	return ""
}

func (x *ParentPinStatus) GetPinnedVersion() uint64 {
	if x != nil {
		return x.PinnedVersion
	}
	return 0
}

func (x *ParentPinStatus) GetCurrentVersion() uint64 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

type RebaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	SchemaId      string                 `protobuf:"bytes,2,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebaseRequest) Reset() {
	*x = RebaseRequest{}
	mi := &file_protoregistry_v1_registry_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebaseRequest) ProtoMessage() {}

func (x *RebaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoregistry_v1_registry_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebaseRequest.ProtoReflect.Descriptor instead.
func (*RebaseRequest) Descriptor() ([]byte, []int) {
	return file_protoregistry_v1_registry_proto_rawDescGZIP(), []int{28}
}

func (x *RebaseRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *RebaseRequest) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

type RebaseResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Version     uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Fingerprint string                 `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	// True when the rebase produced no change — the schema was already
	// pinned to the parent's current state.
	NoChange      bool `protobuf:"varint,3,opt,name=no_change,json=noChange,proto3" json:"no_change,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebaseResponse) Reset() {
	*x = RebaseResponse{}
	mi := &file_protoregistry_v1_registry_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebaseResponse) ProtoMessage() {}

func (x *RebaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoregistry_v1_registry_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebaseResponse.ProtoReflect.Descriptor instead.
func (*RebaseResponse) Descriptor() ([]byte, []int) {
	return file_protoregistry_v1_registry_proto_rawDescGZIP(), []int{29}
}

func (x *RebaseResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RebaseResponse) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *RebaseResponse) GetNoChange() bool {
	if x != nil {
		return x.NoChange
	}
	return false
}

type GetNamespaceChainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNamespaceChainRequest) Reset() {
	*x = GetNamespaceChainRequest{}
	mi := &file_protoregistry_v1_registry_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNamespaceChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNamespaceChainRequest) ProtoMessage() {}

func (x *GetNamespaceChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoregistry_v1_registry_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNamespaceChainRequest.ProtoReflect.Descriptor instead.
func (*GetNamespaceChainRequest) Descriptor() ([]byte, []int) {
	return file_protoregistry_v1_registry_proto_rawDescGZIP(), []int{30}
}

func (x *GetNamespaceChainRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

type GetNamespaceChainResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ordered child → root. The named namespace is at index 0; its parent
	// (if any) at index 1; etc. The implicit __builtins__ and Google WKT
	// tiers are not included.
	NamespaceIds  []string `protobuf:"bytes,1,rep,name=namespace_ids,json=namespaceIds,proto3" json:"namespace_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNamespaceChainResponse) Reset() {
	*x = GetNamespaceChainResponse{}
	mi := &file_protoregistry_v1_registry_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNamespaceChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNamespaceChainResponse) ProtoMessage() {}

func (x *GetNamespaceChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoregistry_v1_registry_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNamespaceChainResponse.ProtoReflect.Descriptor instead.
func (*GetNamespaceChainResponse) Descriptor() ([]byte, []int) {
	return file_protoregistry_v1_registry_proto_rawDescGZIP(), []int{31}
}

func (x *GetNamespaceChainResponse) GetNamespaceIds() []string {
	if x != nil {
		return x.NamespaceIds
	}
	return nil
}

var File_protoregistry_v1_registry_proto protoreflect.FileDescriptor

const file_protoregistry_v1_registry_proto_rawDesc = "" +
	"\n" +
	"\x1fprotoregistry/v1/registry.proto\x12\x10protoregistry.v1\x1a google/protobuf/descriptor.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x93\x03\n" +
	"\x0ePublishRequest\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x12\x1b\n" +
	"\tschema_id\x18\x02 \x01(\tR\bschemaId\x12G\n" +
	"\asources\x18\x03 \x03(\v2-.protoregistry.v1.PublishRequest.SourcesEntryR\asources\x12\x1d\n" +
	"\n" +
	"created_by\x18\x04 \x01(\tR\tcreatedBy\x12J\n" +
	"\bmetadata\x18\x05 \x03(\v2..protoregistry.v1.PublishRequest.MetadataEntryR\bmetadata\x12\x14\n" +
	"\x05force\x18\x06 \x01(\bR\x05force\x1a:\n" +
	"\fSourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"j\n" +
	"\x0fPublishResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12 \n" +
	"\vfingerprint\x18\x02 \x01(\tR\vfingerprint\x12\x1b\n" +
	"\tno_change\x18\x03 \x01(\bR\bnoChange\"3\n" +
	"\x0ePromoteRequest\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\"O\n" +
	"\x0fPromoteResponse\x12<\n" +
	"\bpromoted\x18\x01 \x03(\v2 .protoregistry.v1.PromotedSchemaR\bpromoted\"V\n" +
	"\x0ePromotedSchema\x12\x1b\n" +
	"\tschema_id\x18\x01 \x01(\tR\bschemaId\x12'\n" +
	"\x0fcurrent_version\x18\x02 \x01(\x04R\x0ecurrentVersion\":\n" +
	"\x15DiscardStagingRequest\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\"\x18\n" +
	"\x16DiscardStagingResponse\"\x81\x01\n" +
	"\x0fRollbackRequest\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x12\x1b\n" +
	"\tschema_id\x18\x02 \x01(\tR\bschemaId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\x12\x14\n" +
	"\x05force\x18\x04 \x01(\bR\x05force\"\x12\n" +
	"\x10RollbackResponse\"R\n" +
	"\x10GetSchemaRequest\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x12\x1b\n" +
	"\tschema_id\x18\x02 \x01(\tR\bschemaId\"I\n" +
	"\x11GetSchemaResponse\x124\n" +
	"\x06schema\x18\x01 \x01(\v2\x1c.protoregistry.v1.SchemaInfoR\x06schema\"\xa9\x03\n" +
	"\n" +
	"SchemaInfo\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x12\x1b\n" +
	"\tschema_id\x18\x02 \x01(\tR\bschemaId\x12,\n" +
	"\x0fcurrent_version\x18\x03 \x01(\x04H\x00R\x0ecurrentVersion\x88\x01\x01\x12*\n" +
	"\x0estaged_version\x18\x04 \x01(\x04H\x01R\rstagedVersion\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12F\n" +
	"\bmetadata\x18\x06 \x03(\v2*.protoregistry.v1.SchemaInfo.MetadataEntryR\bmetadata\x12\x1a\n" +
	"\bversions\x18\a \x03(\x04R\bversions\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x12\n" +
	"\x10_current_versionB\x11\n" +
	"\x0f_staged_version\"s\n" +
	"\x12ListSchemasRequest\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"u\n" +
	"\x13ListSchemasResponse\x126\n" +
	"\aschemas\x18\x01 \x03(\v2\x1c.protoregistry.v1.SchemaInfoR\aschemas\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"p\n" +
	"\x14GetDescriptorRequest\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x12\x1b\n" +
	"\tschema_id\x18\x02 \x01(\tR\bschemaId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\"\x85\x01\n" +
	"\x15GetDescriptorResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12R\n" +
	"\x13file_descriptor_set\x18\x02 \x01(\v2\".google.protobuf.FileDescriptorSetR\x11fileDescriptorSet\"l\n" +
	"\x10GetSourceRequest\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x12\x1b\n" +
	"\tschema_id\x18\x02 \x01(\tR\bschemaId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\"\xb5\x01\n" +
	"\x11GetSourceResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12J\n" +
	"\asources\x18\x02 \x03(\v20.protoregistry.v1.GetSourceResponse.SourcesEntryR\asources\x1a:\n" +
	"\fSourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"S\n" +
	"\x15ListNamespacesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\x81\x01\n" +
	"\x16ListNamespacesResponse\x12?\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\v2\x1f.protoregistry.v1.NamespaceInfoR\n" +
	"namespaces\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xaf\x02\n" +
	"\rNamespaceInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12I\n" +
	"\bmetadata\x18\x03 \x03(\v2-.protoregistry.v1.NamespaceInfo.MetadataEntryR\bmetadata\x123\n" +
	"\x13parent_namespace_id\x18\x04 \x01(\tH\x00R\x11parentNamespaceId\x88\x01\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x16\n" +
	"\x14_parent_namespace_id\"\x86\x02\n" +
	"\x16CreateNamespaceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12R\n" +
	"\bmetadata\x18\x02 \x03(\v26.protoregistry.v1.CreateNamespaceRequest.MetadataEntryR\bmetadata\x123\n" +
	"\x13parent_namespace_id\x18\x03 \x01(\tH\x00R\x11parentNamespaceId\x88\x01\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x16\n" +
	"\x14_parent_namespace_id\"\x19\n" +
	"\x17CreateNamespaceResponse\"\x8b\x01\n" +
	"\x19SetNamespaceParentRequest\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x123\n" +
	"\x13parent_namespace_id\x18\x02 \x01(\tH\x00R\x11parentNamespaceId\x88\x01\x01B\x16\n" +
	"\x14_parent_namespace_id\"\x1c\n" +
	"\x1aSetNamespaceParentResponse\"X\n" +
	"\x16GetRebaseStatusRequest\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x12\x1b\n" +
	"\tschema_id\x18\x02 \x01(\tR\bschemaId\"\x8a\x01\n" +
	"\x17GetRebaseStatusResponse\x12D\n" +
	"\fpin_statuses\x18\x01 \x03(\v2!.protoregistry.v1.ParentPinStatusR\vpinStatuses\x12)\n" +
	"\x10rebase_available\x18\x02 \x01(\bR\x0frebaseAvailable\"\xd8\x01\n" +
	"\x0fParentPinStatus\x12.\n" +
	"\x13parent_namespace_id\x18\x01 \x01(\tR\x11parentNamespaceId\x12\"\n" +
	"\rdep_schema_id\x18\x02 \x01(\tR\vdepSchemaId\x12!\n" +
	"\fdep_filename\x18\x03 \x01(\tR\vdepFilename\x12%\n" +
	"\x0epinned_version\x18\x04 \x01(\x04R\rpinnedVersion\x12'\n" +
	"\x0fcurrent_version\x18\x05 \x01(\x04R\x0ecurrentVersion\"O\n" +
	"\rRebaseRequest\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x12\x1b\n" +
	"\tschema_id\x18\x02 \x01(\tR\bschemaId\"i\n" +
	"\x0eRebaseResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12 \n" +
	"\vfingerprint\x18\x02 \x01(\tR\vfingerprint\x12\x1b\n" +
	"\tno_change\x18\x03 \x01(\bR\bnoChange\"=\n" +
	"\x18GetNamespaceChainRequest\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\"@\n" +
	"\x19GetNamespaceChainResponse\x12#\n" +
	"\rnamespace_ids\x18\x01 \x03(\tR\fnamespaceIds2\xb4\n" +
	"\n" +
	"\x0fRegistryService\x12N\n" +
	"\aPublish\x12 .protoregistry.v1.PublishRequest\x1a!.protoregistry.v1.PublishResponse\x12N\n" +
	"\aPromote\x12 .protoregistry.v1.PromoteRequest\x1a!.protoregistry.v1.PromoteResponse\x12c\n" +
	"\x0eDiscardStaging\x12'.protoregistry.v1.DiscardStagingRequest\x1a(.protoregistry.v1.DiscardStagingResponse\x12Q\n" +
	"\bRollback\x12!.protoregistry.v1.RollbackRequest\x1a\".protoregistry.v1.RollbackResponse\x12T\n" +
	"\tGetSchema\x12\".protoregistry.v1.GetSchemaRequest\x1a#.protoregistry.v1.GetSchemaResponse\x12Z\n" +
	"\vListSchemas\x12$.protoregistry.v1.ListSchemasRequest\x1a%.protoregistry.v1.ListSchemasResponse\x12`\n" +
	"\rGetDescriptor\x12&.protoregistry.v1.GetDescriptorRequest\x1a'.protoregistry.v1.GetDescriptorResponse\x12T\n" +
	"\tGetSource\x12\".protoregistry.v1.GetSourceRequest\x1a#.protoregistry.v1.GetSourceResponse\x12c\n" +
	"\x0eListNamespaces\x12'.protoregistry.v1.ListNamespacesRequest\x1a(.protoregistry.v1.ListNamespacesResponse\x12f\n" +
	"\x0fCreateNamespace\x12(.protoregistry.v1.CreateNamespaceRequest\x1a).protoregistry.v1.CreateNamespaceResponse\x12o\n" +
	"\x12SetNamespaceParent\x12+.protoregistry.v1.SetNamespaceParentRequest\x1a,.protoregistry.v1.SetNamespaceParentResponse\x12f\n" +
	"\x0fGetRebaseStatus\x12(.protoregistry.v1.GetRebaseStatusRequest\x1a).protoregistry.v1.GetRebaseStatusResponse\x12K\n" +
	"\x06Rebase\x12\x1f.protoregistry.v1.RebaseRequest\x1a .protoregistry.v1.RebaseResponse\x12l\n" +
	"\x11GetNamespaceChain\x12*.protoregistry.v1.GetNamespaceChainRequest\x1a+.protoregistry.v1.GetNamespaceChainResponseBGZEgithub.com/trendvidia/protoregistry/proto/protoregistry/v1;registrypbb\x06proto3"

var (
	file_protoregistry_v1_registry_proto_rawDescOnce sync.Once
	file_protoregistry_v1_registry_proto_rawDescData []byte
)

func file_protoregistry_v1_registry_proto_rawDescGZIP() []byte {
	file_protoregistry_v1_registry_proto_rawDescOnce.Do(func() {
		file_protoregistry_v1_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protoregistry_v1_registry_proto_rawDesc), len(file_protoregistry_v1_registry_proto_rawDesc)))
	})
	return file_protoregistry_v1_registry_proto_rawDescData
}

var file_protoregistry_v1_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_protoregistry_v1_registry_proto_goTypes = []any{
	(*PublishRequest)(nil),                 // 0: protoregistry.v1.PublishRequest
	(*PublishResponse)(nil),                // 1: protoregistry.v1.PublishResponse
	(*PromoteRequest)(nil),                 // 2: protoregistry.v1.PromoteRequest
	(*PromoteResponse)(nil),                // 3: protoregistry.v1.PromoteResponse
	(*PromotedSchema)(nil),                 // 4: protoregistry.v1.PromotedSchema
	(*DiscardStagingRequest)(nil),          // 5: protoregistry.v1.DiscardStagingRequest
	(*DiscardStagingResponse)(nil),         // 6: protoregistry.v1.DiscardStagingResponse
	(*RollbackRequest)(nil),                // 7: protoregistry.v1.RollbackRequest
	(*RollbackResponse)(nil),               // 8: protoregistry.v1.RollbackResponse
	(*GetSchemaRequest)(nil),               // 9: protoregistry.v1.GetSchemaRequest
	(*GetSchemaResponse)(nil),              // 10: protoregistry.v1.GetSchemaResponse
	(*SchemaInfo)(nil),                     // 11: protoregistry.v1.SchemaInfo
	(*ListSchemasRequest)(nil),             // 12: protoregistry.v1.ListSchemasRequest
	(*ListSchemasResponse)(nil),            // 13: protoregistry.v1.ListSchemasResponse
	(*GetDescriptorRequest)(nil),           // 14: protoregistry.v1.GetDescriptorRequest
	(*GetDescriptorResponse)(nil),          // 15: protoregistry.v1.GetDescriptorResponse
	(*GetSourceRequest)(nil),               // 16: protoregistry.v1.GetSourceRequest
	(*GetSourceResponse)(nil),              // 17: protoregistry.v1.GetSourceResponse
	(*ListNamespacesRequest)(nil),          // 18: protoregistry.v1.ListNamespacesRequest
	(*ListNamespacesResponse)(nil),         // 19: protoregistry.v1.ListNamespacesResponse
	(*NamespaceInfo)(nil),                  // 20: protoregistry.v1.NamespaceInfo
	(*CreateNamespaceRequest)(nil),         // 21: protoregistry.v1.CreateNamespaceRequest
	(*CreateNamespaceResponse)(nil),        // 22: protoregistry.v1.CreateNamespaceResponse
	(*SetNamespaceParentRequest)(nil),      // 23: protoregistry.v1.SetNamespaceParentRequest
	(*SetNamespaceParentResponse)(nil),     // 24: protoregistry.v1.SetNamespaceParentResponse
	(*GetRebaseStatusRequest)(nil),         // 25: protoregistry.v1.GetRebaseStatusRequest
	(*GetRebaseStatusResponse)(nil),        // 26: protoregistry.v1.GetRebaseStatusResponse
	(*ParentPinStatus)(nil),                // 27: protoregistry.v1.ParentPinStatus
	(*RebaseRequest)(nil),                  // 28: protoregistry.v1.RebaseRequest
	(*RebaseResponse)(nil),                 // 29: protoregistry.v1.RebaseResponse
	(*GetNamespaceChainRequest)(nil),       // 30: protoregistry.v1.GetNamespaceChainRequest
	(*GetNamespaceChainResponse)(nil),      // 31: protoregistry.v1.GetNamespaceChainResponse
	nil,                                    // 32: protoregistry.v1.PublishRequest.SourcesEntry
	nil,                                    // 33: protoregistry.v1.PublishRequest.MetadataEntry
	nil,                                    // 34: protoregistry.v1.SchemaInfo.MetadataEntry
	nil,                                    // 35: protoregistry.v1.GetSourceResponse.SourcesEntry
	nil,                                    // 36: protoregistry.v1.NamespaceInfo.MetadataEntry
	nil,                                    // 37: protoregistry.v1.CreateNamespaceRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil),          // 38: google.protobuf.Timestamp
	(*descriptorpb.FileDescriptorSet)(nil), // 39: google.protobuf.FileDescriptorSet
}
var file_protoregistry_v1_registry_proto_depIdxs = []int32{
	32, // 0: protoregistry.v1.PublishRequest.sources:type_name -> protoregistry.v1.PublishRequest.SourcesEntry
	33, // 1: protoregistry.v1.PublishRequest.metadata:type_name -> protoregistry.v1.PublishRequest.MetadataEntry
	4,  // 2: protoregistry.v1.PromoteResponse.promoted:type_name -> protoregistry.v1.PromotedSchema
	11, // 3: protoregistry.v1.GetSchemaResponse.schema:type_name -> protoregistry.v1.SchemaInfo
	38, // 4: protoregistry.v1.SchemaInfo.created_at:type_name -> google.protobuf.Timestamp
	34, // 5: protoregistry.v1.SchemaInfo.metadata:type_name -> protoregistry.v1.SchemaInfo.MetadataEntry
	11, // 6: protoregistry.v1.ListSchemasResponse.schemas:type_name -> protoregistry.v1.SchemaInfo
	39, // 7: protoregistry.v1.GetDescriptorResponse.file_descriptor_set:type_name -> google.protobuf.FileDescriptorSet
	35, // 8: protoregistry.v1.GetSourceResponse.sources:type_name -> protoregistry.v1.GetSourceResponse.SourcesEntry
	20, // 9: protoregistry.v1.ListNamespacesResponse.namespaces:type_name -> protoregistry.v1.NamespaceInfo
	38, // 10: protoregistry.v1.NamespaceInfo.created_at:type_name -> google.protobuf.Timestamp
	36, // 11: protoregistry.v1.NamespaceInfo.metadata:type_name -> protoregistry.v1.NamespaceInfo.MetadataEntry
	37, // 12: protoregistry.v1.CreateNamespaceRequest.metadata:type_name -> protoregistry.v1.CreateNamespaceRequest.MetadataEntry
	27, // 13: protoregistry.v1.GetRebaseStatusResponse.pin_statuses:type_name -> protoregistry.v1.ParentPinStatus
	0,  // 14: protoregistry.v1.RegistryService.Publish:input_type -> protoregistry.v1.PublishRequest
	2,  // 15: protoregistry.v1.RegistryService.Promote:input_type -> protoregistry.v1.PromoteRequest
	5,  // 16: protoregistry.v1.RegistryService.DiscardStaging:input_type -> protoregistry.v1.DiscardStagingRequest
	7,  // 17: protoregistry.v1.RegistryService.Rollback:input_type -> protoregistry.v1.RollbackRequest
	9,  // 18: protoregistry.v1.RegistryService.GetSchema:input_type -> protoregistry.v1.GetSchemaRequest
	12, // 19: protoregistry.v1.RegistryService.ListSchemas:input_type -> protoregistry.v1.ListSchemasRequest
	14, // 20: protoregistry.v1.RegistryService.GetDescriptor:input_type -> protoregistry.v1.GetDescriptorRequest
	16, // 21: protoregistry.v1.RegistryService.GetSource:input_type -> protoregistry.v1.GetSourceRequest
	18, // 22: protoregistry.v1.RegistryService.ListNamespaces:input_type -> protoregistry.v1.ListNamespacesRequest
	21, // 23: protoregistry.v1.RegistryService.CreateNamespace:input_type -> protoregistry.v1.CreateNamespaceRequest
	23, // 24: protoregistry.v1.RegistryService.SetNamespaceParent:input_type -> protoregistry.v1.SetNamespaceParentRequest
	25, // 25: protoregistry.v1.RegistryService.GetRebaseStatus:input_type -> protoregistry.v1.GetRebaseStatusRequest
	28, // 26: protoregistry.v1.RegistryService.Rebase:input_type -> protoregistry.v1.RebaseRequest
	30, // 27: protoregistry.v1.RegistryService.GetNamespaceChain:input_type -> protoregistry.v1.GetNamespaceChainRequest
	1,  // 28: protoregistry.v1.RegistryService.Publish:output_type -> protoregistry.v1.PublishResponse
	3,  // 29: protoregistry.v1.RegistryService.Promote:output_type -> protoregistry.v1.PromoteResponse
	6,  // 30: protoregistry.v1.RegistryService.DiscardStaging:output_type -> protoregistry.v1.DiscardStagingResponse
	8,  // 31: protoregistry.v1.RegistryService.Rollback:output_type -> protoregistry.v1.RollbackResponse
	10, // 32: protoregistry.v1.RegistryService.GetSchema:output_type -> protoregistry.v1.GetSchemaResponse
	13, // 33: protoregistry.v1.RegistryService.ListSchemas:output_type -> protoregistry.v1.ListSchemasResponse
	15, // 34: protoregistry.v1.RegistryService.GetDescriptor:output_type -> protoregistry.v1.GetDescriptorResponse
	17, // 35: protoregistry.v1.RegistryService.GetSource:output_type -> protoregistry.v1.GetSourceResponse
	19, // 36: protoregistry.v1.RegistryService.ListNamespaces:output_type -> protoregistry.v1.ListNamespacesResponse
	22, // 37: protoregistry.v1.RegistryService.CreateNamespace:output_type -> protoregistry.v1.CreateNamespaceResponse
	24, // 38: protoregistry.v1.RegistryService.SetNamespaceParent:output_type -> protoregistry.v1.SetNamespaceParentResponse
	26, // 39: protoregistry.v1.RegistryService.GetRebaseStatus:output_type -> protoregistry.v1.GetRebaseStatusResponse
	29, // 40: protoregistry.v1.RegistryService.Rebase:output_type -> protoregistry.v1.RebaseResponse
	31, // 41: protoregistry.v1.RegistryService.GetNamespaceChain:output_type -> protoregistry.v1.GetNamespaceChainResponse
	28, // [28:42] is the sub-list for method output_type
	14, // [14:28] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_protoregistry_v1_registry_proto_init() }
func file_protoregistry_v1_registry_proto_init() {
	if File_protoregistry_v1_registry_proto != nil {
		return
	}
	file_protoregistry_v1_registry_proto_msgTypes[11].OneofWrappers = []any{}
	file_protoregistry_v1_registry_proto_msgTypes[20].OneofWrappers = []any{}
	file_protoregistry_v1_registry_proto_msgTypes[21].OneofWrappers = []any{}
	file_protoregistry_v1_registry_proto_msgTypes[23].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protoregistry_v1_registry_proto_rawDesc), len(file_protoregistry_v1_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protoregistry_v1_registry_proto_goTypes,
		DependencyIndexes: file_protoregistry_v1_registry_proto_depIdxs,
		MessageInfos:      file_protoregistry_v1_registry_proto_msgTypes,
	}.Build()
	File_protoregistry_v1_registry_proto = out.File
	file_protoregistry_v1_registry_proto_goTypes = nil
	file_protoregistry_v1_registry_proto_depIdxs = nil
}
