// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blobs.sql

package sqlc

import (
	"context"
)

const getBlob = `-- name: GetBlob :one
SELECT namespace_id, sha256, original_source, size_bytes, created_at
FROM proto_blobs
WHERE namespace_id = $1 AND sha256 = $2
`

type GetBlobParams struct {
	NamespaceID string `json:"namespace_id"`
	Sha256      string `json:"sha256"`
}

func (q *Queries) GetBlob(ctx context.Context, arg GetBlobParams) (ProtoBlob, error) {
	row := q.db.QueryRow(ctx, getBlob, arg.NamespaceID, arg.Sha256)
	var i ProtoBlob
	err := row.Scan(
		&i.NamespaceID,
		&i.Sha256,
		&i.OriginalSource,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const getBlobsByHashes = `-- name: GetBlobsByHashes :many
SELECT namespace_id, sha256, original_source, size_bytes, created_at
FROM proto_blobs
WHERE namespace_id = $1 AND sha256 = ANY($2::text[])
`

type GetBlobsByHashesParams struct {
	NamespaceID string   `json:"namespace_id"`
	Column2     []string `json:"column_2"`
}

func (q *Queries) GetBlobsByHashes(ctx context.Context, arg GetBlobsByHashesParams) ([]ProtoBlob, error) {
	rows, err := q.db.Query(ctx, getBlobsByHashes, arg.NamespaceID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProtoBlob{}
	for rows.Next() {
		var i ProtoBlob
		if err := rows.Scan(
			&i.NamespaceID,
			&i.Sha256,
			&i.OriginalSource,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putBlob = `-- name: PutBlob :exec
INSERT INTO proto_blobs (namespace_id, sha256, original_source, size_bytes)
VALUES ($1, $2, $3, $4)
ON CONFLICT (namespace_id, sha256) DO NOTHING
`

type PutBlobParams struct {
	NamespaceID    string `json:"namespace_id"`
	Sha256         string `json:"sha256"`
	OriginalSource []byte `json:"original_source"`
	SizeBytes      int32  `json:"size_bytes"`
}

func (q *Queries) PutBlob(ctx context.Context, arg PutBlobParams) error {
	_, err := q.db.Exec(ctx, putBlob,
		arg.NamespaceID,
		arg.Sha256,
		arg.OriginalSource,
		arg.SizeBytes,
	)
	return err
}
