// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Namespace struct {
	ID        string             `json:"id"`
	CreatedAt time.Time          `json:"created_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	Metadata  []byte             `json:"metadata"`
}

type ProtoBlob struct {
	NamespaceID    string    `json:"namespace_id"`
	Sha256         string    `json:"sha256"`
	OriginalSource []byte    `json:"original_source"`
	SizeBytes      int32     `json:"size_bytes"`
	CreatedAt      time.Time `json:"created_at"`
}

type Schema struct {
	NamespaceID    string             `json:"namespace_id"`
	SchemaID       string             `json:"schema_id"`
	CurrentVersion pgtype.Int8        `json:"current_version"`
	StagedVersion  pgtype.Int8        `json:"staged_version"`
	CreatedAt      time.Time          `json:"created_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	Metadata       []byte             `json:"metadata"`
}

type SchemaVersion struct {
	NamespaceID     string             `json:"namespace_id"`
	SchemaID        string             `json:"schema_id"`
	Version         int64              `json:"version"`
	Compiled        []byte             `json:"compiled"`
	CompilerVersion string             `json:"compiler_version"`
	CreatedAt       time.Time          `json:"created_at"`
	CreatedBy       string             `json:"created_by"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	Metadata        []byte             `json:"metadata"`
}

type SchemaVersionDep struct {
	NamespaceID string `json:"namespace_id"`
	SchemaID    string `json:"schema_id"`
	Version     int64  `json:"version"`
	DepSchemaID string `json:"dep_schema_id"`
	DepFilename string `json:"dep_filename"`
	DepVersion  int64  `json:"dep_version"`
}

type SchemaVersionFile struct {
	NamespaceID string `json:"namespace_id"`
	SchemaID    string `json:"schema_id"`
	Version     int64  `json:"version"`
	Filename    string `json:"filename"`
	BlobSha256  string `json:"blob_sha256"`
}
