// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: namespaces.sql

package sqlc

import (
	"context"
)

const createNamespace = `-- name: CreateNamespace :exec
INSERT INTO namespaces (id, metadata)
VALUES ($1, $2)
`

type CreateNamespaceParams struct {
	ID       string `json:"id"`
	Metadata []byte `json:"metadata"`
}

func (q *Queries) CreateNamespace(ctx context.Context, arg CreateNamespaceParams) error {
	_, err := q.db.Exec(ctx, createNamespace, arg.ID, arg.Metadata)
	return err
}

const getNamespace = `-- name: GetNamespace :one
SELECT id, created_at, deleted_at, metadata
FROM namespaces
WHERE id = $1
`

func (q *Queries) GetNamespace(ctx context.Context, id string) (Namespace, error) {
	row := q.db.QueryRow(ctx, getNamespace, id)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.Metadata,
	)
	return i, err
}

const listNamespaces = `-- name: ListNamespaces :many
SELECT id, created_at, deleted_at, metadata
FROM namespaces
WHERE deleted_at IS NULL
ORDER BY id
`

func (q *Queries) ListNamespaces(ctx context.Context) ([]Namespace, error) {
	rows, err := q.db.Query(ctx, listNamespaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Namespace{}
	for rows.Next() {
		var i Namespace
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNamespacesPage = `-- name: ListNamespacesPage :many
SELECT id, created_at, deleted_at, metadata
FROM namespaces
WHERE deleted_at IS NULL
  AND id > $1
ORDER BY id
LIMIT $2
`

type ListNamespacesPageParams struct {
	ID    string `json:"id"`
	Limit int32  `json:"limit"`
}

// ListNamespacesPage returns at most $2 namespaces whose id is strictly
// greater than $1, ordered by id. Pass an empty string for $1 to start at
// the beginning. Keyset pagination: stable under concurrent inserts/deletes.
func (q *Queries) ListNamespacesPage(ctx context.Context, arg ListNamespacesPageParams) ([]Namespace, error) {
	rows, err := q.db.Query(ctx, listNamespacesPage, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Namespace{}
	for rows.Next() {
		var i Namespace
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteNamespace = `-- name: SoftDeleteNamespace :exec
UPDATE namespaces SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteNamespace(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteNamespace, id)
	return err
}
