// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: parent_events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listNamespaceParentEvents = `-- name: ListNamespaceParentEvents :many
SELECT id, namespace_id, previous_parent_id, new_parent_id, actor_id, occurred_at
FROM namespace_parent_events
WHERE namespace_id = $1
ORDER BY occurred_at DESC, id DESC
LIMIT $2
`

type ListNamespaceParentEventsParams struct {
	NamespaceID string `json:"namespace_id"`
	Limit       int32  `json:"limit"`
}

// ListNamespaceParentEvents returns the re-parenting history for a
// namespace, newest first. Bounded by limit; for full history with
// pagination, use the keyset variant below.
func (q *Queries) ListNamespaceParentEvents(ctx context.Context, arg ListNamespaceParentEventsParams) ([]NamespaceParentEvent, error) {
	rows, err := q.db.Query(ctx, listNamespaceParentEvents, arg.NamespaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NamespaceParentEvent{}
	for rows.Next() {
		var i NamespaceParentEvent
		if err := rows.Scan(
			&i.ID,
			&i.NamespaceID,
			&i.PreviousParentID,
			&i.NewParentID,
			&i.ActorID,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNamespaceParentEventsPage = `-- name: ListNamespaceParentEventsPage :many
SELECT id, namespace_id, previous_parent_id, new_parent_id, actor_id, occurred_at
FROM namespace_parent_events
WHERE namespace_id = $1::text
  AND ($2::bigint = 0 OR id < $2::bigint)
ORDER BY id DESC
LIMIT $3::int
`

type ListNamespaceParentEventsPageParams struct {
	NamespaceID string `json:"namespace_id"`
	AfterID     int64  `json:"after_id"`
	PageLimit   int32  `json:"page_limit"`
}

// ListNamespaceParentEventsPage returns events with id strictly less than
// @after_id (or all events when @after_id is 0), newest first. Keyset
// pagination on the BIGSERIAL primary key — stable under concurrent inserts.
func (q *Queries) ListNamespaceParentEventsPage(ctx context.Context, arg ListNamespaceParentEventsPageParams) ([]NamespaceParentEvent, error) {
	rows, err := q.db.Query(ctx, listNamespaceParentEventsPage, arg.NamespaceID, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NamespaceParentEvent{}
	for rows.Next() {
		var i NamespaceParentEvent
		if err := rows.Scan(
			&i.ID,
			&i.NamespaceID,
			&i.PreviousParentID,
			&i.NewParentID,
			&i.ActorID,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordNamespaceParentEvent = `-- name: RecordNamespaceParentEvent :exec

INSERT INTO namespace_parent_events (
    namespace_id, previous_parent_id, new_parent_id, actor_id
)
VALUES ($1, $2, $3, $4)
`

type RecordNamespaceParentEventParams struct {
	NamespaceID      string      `json:"namespace_id"`
	PreviousParentID pgtype.Text `json:"previous_parent_id"`
	NewParentID      pgtype.Text `json:"new_parent_id"`
	ActorID          string      `json:"actor_id"`
}

// Append-only audit log for namespace re-parenting events. See
// docs/design/namespace-hierarchy.md decision D9.
//
// Phase 1 ships the schema and queries; callers (the SetNamespaceParent
// RPC) wire them up in phase 3.
func (q *Queries) RecordNamespaceParentEvent(ctx context.Context, arg RecordNamespaceParentEventParams) error {
	_, err := q.db.Exec(ctx, recordNamespaceParentEvent,
		arg.NamespaceID,
		arg.PreviousParentID,
		arg.NewParentID,
		arg.ActorID,
	)
	return err
}
