// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recovery.sql

package sqlc

import (
	"context"
)

const loadAllCurrent = `-- name: LoadAllCurrent :many
SELECT
    sv.namespace_id,
    sv.schema_id,
    sv.version,
    sv.compiled,
    sv.compiler_version,
    svf.filename,
    svf.blob_sha256
FROM schemas s
JOIN schema_versions sv
  ON sv.namespace_id = s.namespace_id
 AND sv.schema_id = s.schema_id
 AND sv.version = s.current_version
JOIN schema_version_files svf
  ON svf.namespace_id = sv.namespace_id
 AND svf.schema_id = sv.schema_id
 AND svf.version = sv.version
WHERE s.current_version IS NOT NULL
  AND s.deleted_at IS NULL
ORDER BY sv.namespace_id, sv.schema_id, svf.filename
`

type LoadAllCurrentRow struct {
	NamespaceID     string `json:"namespace_id"`
	SchemaID        string `json:"schema_id"`
	Version         int64  `json:"version"`
	Compiled        []byte `json:"compiled"`
	CompilerVersion string `json:"compiler_version"`
	Filename        string `json:"filename"`
	BlobSha256      string `json:"blob_sha256"`
}

func (q *Queries) LoadAllCurrent(ctx context.Context) ([]LoadAllCurrentRow, error) {
	rows, err := q.db.Query(ctx, loadAllCurrent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadAllCurrentRow{}
	for rows.Next() {
		var i LoadAllCurrentRow
		if err := rows.Scan(
			&i.NamespaceID,
			&i.SchemaID,
			&i.Version,
			&i.Compiled,
			&i.CompilerVersion,
			&i.Filename,
			&i.BlobSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadNamespaceCurrent = `-- name: LoadNamespaceCurrent :many
SELECT
    sv.namespace_id,
    sv.schema_id,
    sv.version,
    sv.compiled,
    sv.compiler_version,
    svf.filename,
    svf.blob_sha256
FROM schemas s
JOIN schema_versions sv
  ON sv.namespace_id = s.namespace_id
 AND sv.schema_id = s.schema_id
 AND sv.version = s.current_version
JOIN schema_version_files svf
  ON svf.namespace_id = sv.namespace_id
 AND svf.schema_id = sv.schema_id
 AND svf.version = sv.version
WHERE s.namespace_id = $1
  AND s.current_version IS NOT NULL
  AND s.deleted_at IS NULL
ORDER BY sv.schema_id, svf.filename
`

type LoadNamespaceCurrentRow struct {
	NamespaceID     string `json:"namespace_id"`
	SchemaID        string `json:"schema_id"`
	Version         int64  `json:"version"`
	Compiled        []byte `json:"compiled"`
	CompilerVersion string `json:"compiler_version"`
	Filename        string `json:"filename"`
	BlobSha256      string `json:"blob_sha256"`
}

func (q *Queries) LoadNamespaceCurrent(ctx context.Context, namespaceID string) ([]LoadNamespaceCurrentRow, error) {
	rows, err := q.db.Query(ctx, loadNamespaceCurrent, namespaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadNamespaceCurrentRow{}
	for rows.Next() {
		var i LoadNamespaceCurrentRow
		if err := rows.Scan(
			&i.NamespaceID,
			&i.SchemaID,
			&i.Version,
			&i.Compiled,
			&i.CompilerVersion,
			&i.Filename,
			&i.BlobSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadNamespaceProposed = `-- name: LoadNamespaceProposed :many
SELECT
    sv.namespace_id,
    sv.schema_id,
    sv.version,
    sv.compiled,
    sv.compiler_version,
    svf.filename,
    svf.blob_sha256
FROM schemas s
JOIN schema_versions sv
  ON sv.namespace_id = s.namespace_id
 AND sv.schema_id = s.schema_id
 AND sv.version = COALESCE(s.staged_version, s.current_version)
JOIN schema_version_files svf
  ON svf.namespace_id = sv.namespace_id
 AND svf.schema_id = sv.schema_id
 AND svf.version = sv.version
WHERE s.namespace_id = $1
  AND COALESCE(s.staged_version, s.current_version) IS NOT NULL
  AND s.deleted_at IS NULL
ORDER BY sv.schema_id, svf.filename
`

type LoadNamespaceProposedRow struct {
	NamespaceID     string `json:"namespace_id"`
	SchemaID        string `json:"schema_id"`
	Version         int64  `json:"version"`
	Compiled        []byte `json:"compiled"`
	CompilerVersion string `json:"compiler_version"`
	Filename        string `json:"filename"`
	BlobSha256      string `json:"blob_sha256"`
}

func (q *Queries) LoadNamespaceProposed(ctx context.Context, namespaceID string) ([]LoadNamespaceProposedRow, error) {
	rows, err := q.db.Query(ctx, loadNamespaceProposed, namespaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadNamespaceProposedRow{}
	for rows.Next() {
		var i LoadNamespaceProposedRow
		if err := rows.Scan(
			&i.NamespaceID,
			&i.SchemaID,
			&i.Version,
			&i.Compiled,
			&i.CompilerVersion,
			&i.Filename,
			&i.BlobSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
