// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schemas.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearStagedVersion = `-- name: ClearStagedVersion :exec
UPDATE schemas SET staged_version = NULL
WHERE namespace_id = $1 AND schema_id = $2
`

type ClearStagedVersionParams struct {
	NamespaceID string `json:"namespace_id"`
	SchemaID    string `json:"schema_id"`
}

func (q *Queries) ClearStagedVersion(ctx context.Context, arg ClearStagedVersionParams) error {
	_, err := q.db.Exec(ctx, clearStagedVersion, arg.NamespaceID, arg.SchemaID)
	return err
}

const createSchema = `-- name: CreateSchema :exec
INSERT INTO schemas (namespace_id, schema_id, metadata)
VALUES ($1, $2, $3)
`

type CreateSchemaParams struct {
	NamespaceID string `json:"namespace_id"`
	SchemaID    string `json:"schema_id"`
	Metadata    []byte `json:"metadata"`
}

func (q *Queries) CreateSchema(ctx context.Context, arg CreateSchemaParams) error {
	_, err := q.db.Exec(ctx, createSchema, arg.NamespaceID, arg.SchemaID, arg.Metadata)
	return err
}

const discardAllStaged = `-- name: DiscardAllStaged :exec
UPDATE schemas
SET staged_version = NULL
WHERE namespace_id = $1
  AND staged_version IS NOT NULL
`

func (q *Queries) DiscardAllStaged(ctx context.Context, namespaceID string) error {
	_, err := q.db.Exec(ctx, discardAllStaged, namespaceID)
	return err
}

const getSchema = `-- name: GetSchema :one
SELECT namespace_id, schema_id, current_version, staged_version,
       created_at, deleted_at, metadata
FROM schemas
WHERE namespace_id = $1 AND schema_id = $2
`

type GetSchemaParams struct {
	NamespaceID string `json:"namespace_id"`
	SchemaID    string `json:"schema_id"`
}

func (q *Queries) GetSchema(ctx context.Context, arg GetSchemaParams) (Schema, error) {
	row := q.db.QueryRow(ctx, getSchema, arg.NamespaceID, arg.SchemaID)
	var i Schema
	err := row.Scan(
		&i.NamespaceID,
		&i.SchemaID,
		&i.CurrentVersion,
		&i.StagedVersion,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.Metadata,
	)
	return i, err
}

const getSchemaForUpdate = `-- name: GetSchemaForUpdate :one
SELECT namespace_id, schema_id, current_version, staged_version,
       created_at, deleted_at, metadata
FROM schemas
WHERE namespace_id = $1 AND schema_id = $2
FOR UPDATE
`

type GetSchemaForUpdateParams struct {
	NamespaceID string `json:"namespace_id"`
	SchemaID    string `json:"schema_id"`
}

func (q *Queries) GetSchemaForUpdate(ctx context.Context, arg GetSchemaForUpdateParams) (Schema, error) {
	row := q.db.QueryRow(ctx, getSchemaForUpdate, arg.NamespaceID, arg.SchemaID)
	var i Schema
	err := row.Scan(
		&i.NamespaceID,
		&i.SchemaID,
		&i.CurrentVersion,
		&i.StagedVersion,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.Metadata,
	)
	return i, err
}

const getStagedSchemas = `-- name: GetStagedSchemas :many
SELECT namespace_id, schema_id, current_version, staged_version,
       created_at, deleted_at, metadata
FROM schemas
WHERE namespace_id = $1
  AND staged_version IS NOT NULL
  AND deleted_at IS NULL
`

func (q *Queries) GetStagedSchemas(ctx context.Context, namespaceID string) ([]Schema, error) {
	rows, err := q.db.Query(ctx, getStagedSchemas, namespaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schema{}
	for rows.Next() {
		var i Schema
		if err := rows.Scan(
			&i.NamespaceID,
			&i.SchemaID,
			&i.CurrentVersion,
			&i.StagedVersion,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchemas = `-- name: ListSchemas :many
SELECT namespace_id, schema_id, current_version, staged_version,
       created_at, deleted_at, metadata
FROM schemas
WHERE namespace_id = $1 AND deleted_at IS NULL
ORDER BY schema_id
`

func (q *Queries) ListSchemas(ctx context.Context, namespaceID string) ([]Schema, error) {
	rows, err := q.db.Query(ctx, listSchemas, namespaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schema{}
	for rows.Next() {
		var i Schema
		if err := rows.Scan(
			&i.NamespaceID,
			&i.SchemaID,
			&i.CurrentVersion,
			&i.StagedVersion,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchemasPage = `-- name: ListSchemasPage :many
SELECT namespace_id, schema_id, current_version, staged_version,
       created_at, deleted_at, metadata
FROM schemas
WHERE namespace_id = $1 AND deleted_at IS NULL
  AND schema_id > $2
ORDER BY schema_id
LIMIT $3
`

type ListSchemasPageParams struct {
	NamespaceID string `json:"namespace_id"`
	SchemaID    string `json:"schema_id"`
	Limit       int32  `json:"limit"`
}

// ListSchemasPage is the keyset-paginated variant. Returns at most $3 schemas
// in the namespace whose schema_id is strictly greater than $2, ordered by
// schema_id. Pass an empty string for $2 to start at the beginning.
func (q *Queries) ListSchemasPage(ctx context.Context, arg ListSchemasPageParams) ([]Schema, error) {
	rows, err := q.db.Query(ctx, listSchemasPage, arg.NamespaceID, arg.SchemaID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schema{}
	for rows.Next() {
		var i Schema
		if err := rows.Scan(
			&i.NamespaceID,
			&i.SchemaID,
			&i.CurrentVersion,
			&i.StagedVersion,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteAllStaged = `-- name: PromoteAllStaged :many
UPDATE schemas
SET current_version = staged_version,
    staged_version = NULL
WHERE namespace_id = $1
  AND staged_version IS NOT NULL
RETURNING schema_id, current_version
`

type PromoteAllStagedRow struct {
	SchemaID       string      `json:"schema_id"`
	CurrentVersion pgtype.Int8 `json:"current_version"`
}

func (q *Queries) PromoteAllStaged(ctx context.Context, namespaceID string) ([]PromoteAllStagedRow, error) {
	rows, err := q.db.Query(ctx, promoteAllStaged, namespaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PromoteAllStagedRow{}
	for rows.Next() {
		var i PromoteAllStagedRow
		if err := rows.Scan(&i.SchemaID, &i.CurrentVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCurrentVersion = `-- name: SetCurrentVersion :exec
UPDATE schemas SET current_version = $3
WHERE namespace_id = $1 AND schema_id = $2
`

type SetCurrentVersionParams struct {
	NamespaceID    string      `json:"namespace_id"`
	SchemaID       string      `json:"schema_id"`
	CurrentVersion pgtype.Int8 `json:"current_version"`
}

func (q *Queries) SetCurrentVersion(ctx context.Context, arg SetCurrentVersionParams) error {
	_, err := q.db.Exec(ctx, setCurrentVersion, arg.NamespaceID, arg.SchemaID, arg.CurrentVersion)
	return err
}

const setStagedVersion = `-- name: SetStagedVersion :exec
UPDATE schemas SET staged_version = $3
WHERE namespace_id = $1 AND schema_id = $2
`

type SetStagedVersionParams struct {
	NamespaceID   string      `json:"namespace_id"`
	SchemaID      string      `json:"schema_id"`
	StagedVersion pgtype.Int8 `json:"staged_version"`
}

func (q *Queries) SetStagedVersion(ctx context.Context, arg SetStagedVersionParams) error {
	_, err := q.db.Exec(ctx, setStagedVersion, arg.NamespaceID, arg.SchemaID, arg.StagedVersion)
	return err
}

const softDeleteSchema = `-- name: SoftDeleteSchema :exec
UPDATE schemas SET deleted_at = now()
WHERE namespace_id = $1 AND schema_id = $2 AND deleted_at IS NULL
`

type SoftDeleteSchemaParams struct {
	NamespaceID string `json:"namespace_id"`
	SchemaID    string `json:"schema_id"`
}

func (q *Queries) SoftDeleteSchema(ctx context.Context, arg SoftDeleteSchemaParams) error {
	_, err := q.db.Exec(ctx, softDeleteSchema, arg.NamespaceID, arg.SchemaID)
	return err
}
