// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: versions.sql

package sqlc

import (
	"context"
)

const getDependents = `-- name: GetDependents :many
SELECT DISTINCT schema_id, version
FROM schema_version_deps
WHERE namespace_id = $1 AND dep_schema_id = $2
`

type GetDependentsParams struct {
	NamespaceID string `json:"namespace_id"`
	DepSchemaID string `json:"dep_schema_id"`
}

type GetDependentsRow struct {
	SchemaID string `json:"schema_id"`
	Version  int64  `json:"version"`
}

func (q *Queries) GetDependents(ctx context.Context, arg GetDependentsParams) ([]GetDependentsRow, error) {
	rows, err := q.db.Query(ctx, getDependents, arg.NamespaceID, arg.DepSchemaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDependentsRow{}
	for rows.Next() {
		var i GetDependentsRow
		if err := rows.Scan(&i.SchemaID, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVersion = `-- name: GetVersion :one
SELECT namespace_id, schema_id, version, compiled, compiler_version,
       created_at, created_by, deleted_at, metadata
FROM schema_versions
WHERE namespace_id = $1 AND schema_id = $2 AND version = $3
`

type GetVersionParams struct {
	NamespaceID string `json:"namespace_id"`
	SchemaID    string `json:"schema_id"`
	Version     int64  `json:"version"`
}

func (q *Queries) GetVersion(ctx context.Context, arg GetVersionParams) (SchemaVersion, error) {
	row := q.db.QueryRow(ctx, getVersion, arg.NamespaceID, arg.SchemaID, arg.Version)
	var i SchemaVersion
	err := row.Scan(
		&i.NamespaceID,
		&i.SchemaID,
		&i.Version,
		&i.Compiled,
		&i.CompilerVersion,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.Metadata,
	)
	return i, err
}

const getVersionDeps = `-- name: GetVersionDeps :many
SELECT namespace_id, schema_id, version, dep_schema_id, dep_filename, dep_version
FROM schema_version_deps
WHERE namespace_id = $1 AND schema_id = $2 AND version = $3
`

type GetVersionDepsParams struct {
	NamespaceID string `json:"namespace_id"`
	SchemaID    string `json:"schema_id"`
	Version     int64  `json:"version"`
}

func (q *Queries) GetVersionDeps(ctx context.Context, arg GetVersionDepsParams) ([]SchemaVersionDep, error) {
	rows, err := q.db.Query(ctx, getVersionDeps, arg.NamespaceID, arg.SchemaID, arg.Version)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SchemaVersionDep{}
	for rows.Next() {
		var i SchemaVersionDep
		if err := rows.Scan(
			&i.NamespaceID,
			&i.SchemaID,
			&i.Version,
			&i.DepSchemaID,
			&i.DepFilename,
			&i.DepVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVersionFiles = `-- name: GetVersionFiles :many
SELECT namespace_id, schema_id, version, filename, blob_sha256
FROM schema_version_files
WHERE namespace_id = $1 AND schema_id = $2 AND version = $3
ORDER BY filename
`

type GetVersionFilesParams struct {
	NamespaceID string `json:"namespace_id"`
	SchemaID    string `json:"schema_id"`
	Version     int64  `json:"version"`
}

func (q *Queries) GetVersionFiles(ctx context.Context, arg GetVersionFilesParams) ([]SchemaVersionFile, error) {
	rows, err := q.db.Query(ctx, getVersionFiles, arg.NamespaceID, arg.SchemaID, arg.Version)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SchemaVersionFile{}
	for rows.Next() {
		var i SchemaVersionFile
		if err := rows.Scan(
			&i.NamespaceID,
			&i.SchemaID,
			&i.Version,
			&i.Filename,
			&i.BlobSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertVersion = `-- name: InsertVersion :exec
INSERT INTO schema_versions (namespace_id, schema_id, version, compiled, compiler_version, created_by, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertVersionParams struct {
	NamespaceID     string `json:"namespace_id"`
	SchemaID        string `json:"schema_id"`
	Version         int64  `json:"version"`
	Compiled        []byte `json:"compiled"`
	CompilerVersion string `json:"compiler_version"`
	CreatedBy       string `json:"created_by"`
	Metadata        []byte `json:"metadata"`
}

func (q *Queries) InsertVersion(ctx context.Context, arg InsertVersionParams) error {
	_, err := q.db.Exec(ctx, insertVersion,
		arg.NamespaceID,
		arg.SchemaID,
		arg.Version,
		arg.Compiled,
		arg.CompilerVersion,
		arg.CreatedBy,
		arg.Metadata,
	)
	return err
}

const insertVersionDep = `-- name: InsertVersionDep :exec
INSERT INTO schema_version_deps (namespace_id, schema_id, version, dep_schema_id, dep_filename, dep_version)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertVersionDepParams struct {
	NamespaceID string `json:"namespace_id"`
	SchemaID    string `json:"schema_id"`
	Version     int64  `json:"version"`
	DepSchemaID string `json:"dep_schema_id"`
	DepFilename string `json:"dep_filename"`
	DepVersion  int64  `json:"dep_version"`
}

func (q *Queries) InsertVersionDep(ctx context.Context, arg InsertVersionDepParams) error {
	_, err := q.db.Exec(ctx, insertVersionDep,
		arg.NamespaceID,
		arg.SchemaID,
		arg.Version,
		arg.DepSchemaID,
		arg.DepFilename,
		arg.DepVersion,
	)
	return err
}

const insertVersionFile = `-- name: InsertVersionFile :exec
INSERT INTO schema_version_files (namespace_id, schema_id, version, filename, blob_sha256)
VALUES ($1, $2, $3, $4, $5)
`

type InsertVersionFileParams struct {
	NamespaceID string `json:"namespace_id"`
	SchemaID    string `json:"schema_id"`
	Version     int64  `json:"version"`
	Filename    string `json:"filename"`
	BlobSha256  string `json:"blob_sha256"`
}

func (q *Queries) InsertVersionFile(ctx context.Context, arg InsertVersionFileParams) error {
	_, err := q.db.Exec(ctx, insertVersionFile,
		arg.NamespaceID,
		arg.SchemaID,
		arg.Version,
		arg.Filename,
		arg.BlobSha256,
	)
	return err
}

const listVersions = `-- name: ListVersions :many
SELECT version
FROM schema_versions
WHERE namespace_id = $1 AND schema_id = $2 AND deleted_at IS NULL
ORDER BY version
`

type ListVersionsParams struct {
	NamespaceID string `json:"namespace_id"`
	SchemaID    string `json:"schema_id"`
}

func (q *Queries) ListVersions(ctx context.Context, arg ListVersionsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listVersions, arg.NamespaceID, arg.SchemaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var version int64
		if err := rows.Scan(&version); err != nil {
			return nil, err
		}
		items = append(items, version)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteVersion = `-- name: SoftDeleteVersion :exec
UPDATE schema_versions SET deleted_at = now()
WHERE namespace_id = $1 AND schema_id = $2 AND version = $3
`

type SoftDeleteVersionParams struct {
	NamespaceID string `json:"namespace_id"`
	SchemaID    string `json:"schema_id"`
	Version     int64  `json:"version"`
}

func (q *Queries) SoftDeleteVersion(ctx context.Context, arg SoftDeleteVersionParams) error {
	_, err := q.db.Exec(ctx, softDeleteVersion, arg.NamespaceID, arg.SchemaID, arg.Version)
	return err
}
